/* glycin-2.vapi generated by vapigen, do not modify. */

[CCode (cprefix = "Gly", gir_namespace = "Gly", gir_version = "2", lower_case_cprefix = "gly_")]
namespace Gly {
	[CCode (cheader_filename = "glycin.h", copy_function = "gly_cicp_copy", free_function = "gly_cicp_free", type_id = "gly_cicp_get_type ()")]
	[Compact]
	[Version (since = "2.0")]
	public class Cicp {
		public uint8 color_primaries;
		public uint8 matrix_coefficients;
		public uint8 transfer_characteristics;
		public uint8 video_full_range_flag;
		public Gly.Cicp copy ();
		public void free ();
	}
	[CCode (cheader_filename = "glycin.h", type_id = "gly_creator_get_type ()")]
	[Version (since = "2.0")]
	public class Creator : GLib.Object {
		[CCode (has_construct_function = false)]
		public Creator (string mime_type) throws GLib.Error;
		public Gly.NewFrame add_frame (uint32 width, uint32 height, Gly.MemoryFormat memory_format, GLib.Bytes texture) throws GLib.Error;
		public Gly.NewFrame add_frame_with_stride (uint32 width, uint32 height, uint32 stride, Gly.MemoryFormat memory_format, GLib.Bytes texture) throws GLib.Error;
		public bool add_metadata_key_value (string key, string value);
		public Gly.EncodedImage? create () throws GLib.Error;
		public async Gly.EncodedImage create_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public bool set_encoding_compression (uint8 compression);
		public bool set_encoding_quality (uint8 quality);
		public bool set_sandbox_selector (Gly.SandboxSelector sandbox_selector);
		[NoAccessorMethod]
		public string mime_type { owned get; construct; }
		[NoAccessorMethod]
		public Gly.SandboxSelector sandbox_selector { get; set; }
	}
	[CCode (cheader_filename = "glycin.h", type_id = "gly_encoded_image_get_type ()")]
	[Version (since = "2.0")]
	public class EncodedImage : GLib.Object {
		[CCode (has_construct_function = false)]
		protected EncodedImage ();
		public GLib.Bytes get_data ();
		public GLib.Bytes data { owned get; }
	}
	[CCode (cheader_filename = "glycin.h", type_id = "gly_frame_get_type ()")]
	[Version (since = "2.0")]
	public class Frame : GLib.Object {
		[CCode (has_construct_function = false)]
		protected Frame ();
		public unowned GLib.Bytes get_buf_bytes ();
		public Gly.Cicp? get_color_cicp ();
		public int64 get_delay ();
		public uint32 get_height ();
		public Gly.MemoryFormat get_memory_format ();
		public uint32 get_stride ();
		public uint32 get_width ();
	}
	[CCode (cheader_filename = "glycin.h", type_id = "gly_frame_request_get_type ()")]
	[Version (since = "2.0")]
	public class FrameRequest : GLib.Object {
		[CCode (has_construct_function = false)]
		public FrameRequest ();
		[Version (since = "2.0.1")]
		public void set_loop_animation (bool loop_animation);
		public void set_scale (uint32 width, uint32 height);
		[NoAccessorMethod]
		public bool loop_animation { get; set; }
		[NoAccessorMethod]
		public uint scale_height { get; }
		[NoAccessorMethod]
		public uint scale_width { get; }
	}
	[CCode (cheader_filename = "glycin.h", type_id = "gly_image_get_type ()")]
	[Version (since = "2.0")]
	public class Image : GLib.Object {
		[CCode (has_construct_function = false)]
		protected Image ();
		public uint32 get_height ();
		public string? get_metadata_key_value (string key);
		[CCode (array_length = false, array_null_terminated = true)]
		public string[] get_metadata_keys ();
		public unowned string get_mime_type ();
		public Gly.Frame get_specific_frame (Gly.FrameRequest frame_request) throws GLib.Error;
		public async Gly.Frame get_specific_frame_async (Gly.FrameRequest frame_request, GLib.Cancellable? cancellable) throws GLib.Error;
		public uint16 get_transformation_orientation ();
		public uint32 get_width ();
		public Gly.Frame next_frame () throws GLib.Error;
		public async Gly.Frame next_frame_async (GLib.Cancellable? cancellable) throws GLib.Error;
	}
	[CCode (cheader_filename = "glycin.h", type_id = "gly_loader_get_type ()")]
	[Version (since = "2.0")]
	public class Loader : GLib.Object {
		[CCode (has_construct_function = false)]
		public Loader (GLib.File file);
		[CCode (has_construct_function = false)]
		public Loader.for_bytes (GLib.Bytes bytes);
		[CCode (has_construct_function = false)]
		public Loader.for_stream (GLib.InputStream stream);
		[CCode (array_length = false, array_null_terminated = true)]
		public static string[] get_mime_types ();
		[CCode (array_length = false, array_null_terminated = true)]
		public static async string[] get_mime_types_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public Gly.Image load () throws GLib.Error;
		public async Gly.Image load_async (GLib.Cancellable? cancellable) throws GLib.Error;
		public void set_accepted_memory_formats (Gly.MemoryFormatSelection memory_format_selection);
		public void set_apply_transformations (bool apply_transformations);
		public void set_sandbox_selector (Gly.SandboxSelector sandbox_selector);
		[NoAccessorMethod]
		public bool apply_transformation { get; set; }
		[NoAccessorMethod]
		public GLib.Bytes bytes { owned get; construct; }
		[NoAccessorMethod]
		public GLib.Cancellable cancellable { owned get; set; }
		[NoAccessorMethod]
		public GLib.File file { owned get; construct; }
		[NoAccessorMethod]
		public Gly.MemoryFormatSelection memory_format_selection { get; set; }
		[NoAccessorMethod]
		public Gly.SandboxSelector sandbox_selector { get; set; }
		[NoAccessorMethod]
		public GLib.InputStream stream { owned get; construct; }
	}
	[CCode (cheader_filename = "glycin.h", type_id = "gly_new_frame_get_type ()")]
	[Version (since = "2.0")]
	public class NewFrame : GLib.Object {
		[CCode (has_construct_function = false)]
		protected NewFrame ();
		public bool set_color_icc_profile (GLib.Bytes icc_profile);
	}
	[CCode (cheader_filename = "glycin.h", cprefix = "GLY_MEMORY_", type_id = "gly_memory_format_get_type ()")]
	[Version (since = "2.0")]
	public enum MemoryFormat {
		B8G8R8A8_PREMULTIPLIED,
		A8R8G8B8_PREMULTIPLIED,
		R8G8B8A8_PREMULTIPLIED,
		B8G8R8A8,
		A8R8G8B8,
		R8G8B8A8,
		A8B8G8R8,
		R8G8B8,
		B8G8R8,
		R16G16B16,
		R16G16B16A16_PREMULTIPLIED,
		R16G16B16A16,
		R16G16B16_FLOAT,
		R16G16B16A16_FLOAT,
		R32G32B32_FLOAT,
		R32G32B32A32_FLOAT_PREMULTIPLIED,
		R32G32B32A32_FLOAT,
		G8A8_PREMULTIPLIED,
		G8A8,
		G8,
		G16A16_PREMULTIPLIED,
		G16A16,
		G16;
		public bool has_alpha ();
		public bool is_premultiplied ();
	}
	[CCode (cheader_filename = "glycin.h", cprefix = "GLY_MEMORY_SELECTION_", type_id = "gly_memory_format_selection_get_type ()")]
	[Flags]
	[Version (since = "2.0")]
	public enum MemoryFormatSelection {
		B8G8R8A8_PREMULTIPLIED,
		A8R8G8B8_PREMULTIPLIED,
		R8G8B8A8_PREMULTIPLIED,
		B8G8R8A8,
		A8R8G8B8,
		R8G8B8A8,
		A8B8G8R8,
		R8G8B8,
		B8G8R8,
		R16G16B16,
		R16G16B16A16_PREMULTIPLIED,
		R16G16B16A16,
		R16G16B16_FLOAT,
		R16G16B16A16_FLOAT,
		R32G32B32_FLOAT,
		R32G32B32A32_FLOAT_PREMULTIPLIED,
		R32G32B32A32_FLOAT,
		G8A8_PREMULTIPLIED,
		G8A8,
		G8,
		G16A16_PREMULTIPLIED,
		G16A16,
		G16
	}
	[CCode (cheader_filename = "glycin.h", cprefix = "GLY_SANDBOX_SELECTOR_", type_id = "gly_sandbox_selector_get_type ()")]
	[Version (since = "2.0")]
	public enum SandboxSelector {
		AUTO,
		BWRAP,
		FLATPAK_SPAWN,
		NOT_SANDBOXED
	}
	[CCode (cheader_filename = "glycin.h", cprefix = "GLY_LOADER_ERROR_", type_id = "gly_loader_error_get_type ()")]
	[Version (since = "2.0")]
	public errordomain LoaderError {
		FAILED,
		UNKNOWN_IMAGE_FORMAT,
		[Version (since = "2.0.1")]
		NO_MORE_FRAMES;
		public static GLib.Quark quark ();
	}
	[CCode (cheader_filename = "glycin.h", has_target = false)]
	public delegate void LoaderGetMimeTypesDoneFunc ([CCode (array_length = false, array_null_terminated = true)] string[] mime_types, void* data);
	[CCode (cheader_filename = "glycin.h")]
	[Version (replacement = "LoaderError.quark")]
	public static GLib.Quark loader_error_quark ();
	[CCode (cheader_filename = "glycin.h")]
	[Version (replacement = "MemoryFormat.has_alpha", since = "2.0")]
	public static bool memory_format_has_alpha (Gly.MemoryFormat memory_format);
	[CCode (cheader_filename = "glycin.h")]
	[Version (replacement = "MemoryFormat.is_premultiplied", since = "2.0")]
	public static bool memory_format_is_premultiplied (Gly.MemoryFormat memory_format);
}
